# Generated by Django 2.2.1 on 2019-08-17 12:30

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('recipient_email', models.TextField()),
                ('subject', models.TextField()),
                ('content', models.TextField()),
                ('template_type', models.TextField()),
                ('extra_data', models.TextField()),
                ('full_data', models.TextField()),
                ('template_id', models.TextField()),
                ('categories', models.TextField()),
                ('error', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('in_review', 'In Review'), ('sent', 'Sent'), ('delivered', 'Delivered')], db_index=True, max_length=16, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
