# Generated by Django 2.2.1 on 2019-08-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salalem_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='extra_data',
            field=models.TextField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(blank=True, choices=[('in_review', 'In Review'), ('approved', 'Approved'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('error', 'Error')], db_index=True, max_length=16, null=True),
        ),
    ]
