# Generated by Django 2.1.4 on 2019-02-20 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salalem_notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='action_object_content_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='actor_content_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='target_content_type',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
