# Generated by Django 2.2.1 on 2019-08-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salalem_notifications', '0002_auto_20190829_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
